### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by kmelihk** [mmcc-xx/gesturesensor#1]
Mosquitto in Home Assistant doesn't allow anonymous logins any more. Any plans to update for authentication?

**Comment by kmelihk** [comment]
I was able to add the following line to config.py and can now authenticate.

client.username_pw_set("username", password="password")

**Comment by msolomos** [comment]
> client.username_pw_set("username", password="password")

have you managed to run the container?

**Comment by kmelihk** [comment]
yes, container runs, but needed a bit of work to get it running, can't remember the details now.

**Comment by msolomos** [comment]
> yes, container runs, but needed a bit of work to get it running, can't remember the details now.

Also can you share the requirements.txt please?  Maybe you've changed some libraries.

**Comment by msolomos** [comment]
I've managed to build the image and the container is running. 
I get an exception when a new detect is fired

> 2024-02-13 01:41:34 2024-02-12 23:41:34,902 - INFO - Connected to MQTT broker
2024-02-13 01:42:58 2024-02-12 23:42:58,915 - DEBUG - Starting new HTTP connection (1): 192.168.70.240:3000
2024-02-13 01:42:58 2024-02-12 23:42:58,943 - DEBUG - http://192.168.70.240:3000 "GET /api/recognize?url=http://192.168.70.40:5000/api/frontdoor_camera2/latest.jpg&attempts=1&camera=frontdoor_camera2 HTTP/1.1" 403 136
2024-02-13 01:42:58 Exception in thread Thread-1:
2024-02-13 01:42:58 Traceback (most recent call last):
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 971, in json
2024-02-13 01:42:58     return complexjson.loads(self.text, **kwargs)
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
2024-02-13 01:42:58     return _default_decoder.decode(s)
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
2024-02-13 01:42:58     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
2024-02-13 01:42:58     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-02-13 01:42:58 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-02-13 01:42:58 
2024-02-13 01:42:58 During handling of the above exception, another exception occurred:
2024-02-13 01:42:58 
2024-02-13 01:42:58 Traceback (most recent call last):
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2024-02-13 01:42:58     self.run()
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/threading.py", line 870, in run
2024-02-13 01:42:58     self._target(*self._args, **self._kwargs)
2024-02-13 01:42:58   File "/code/gesturedetection.py", line 79, in lookforhands
2024-02-13 01:42:58     matches = getmatches(cameraname)
2024-02-13 01:42:58   File "/code/gesturedetection.py", line 39, in getmatches
2024-02-13 01:42:58     output = response.json()
2024-02-13 01:42:58   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 975, in json
2024-02-13 01:42:58     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-02-13 01:42:58 requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Any help would be much appreciated ...

**Comment by kmelihk** [comment]
i'm not the programmer of this so i can't tell you much but looking at it, it seems your camera name may be different than what Frigate has them. Otherwise I have no idea and I recommend you open another issue, although pretty sure this is an unsupported project.

**Comment by msolomos** [comment]
Dear kmelihk, 
You are right that this is not a supported project. I've contacted the code owner several times without any reply.
It is a shame because this project is what I was looking for and with some extra work it could be a good addon for HA.
Unfortunately my knowledge on docker and python is limited so I can't make it work.

I know you are not the programmer. And thank you for getting back to me more than once.
If you can take a moment and want to have a 2nd look on the error I would appreciate very much.

**Comment by kmelihk** [comment]
Looks like your double-take is returning a forbidden error code, not responding to api request. Which double-take repo did you install from? Are you using the latest fork here: https://github.com/skrashevich/double-take ? Make sure your double-take configuration has the line: reject_unauthorized: false

**Comment by msolomos** [comment]
Yes, I am using the latest fork indeed. 
I will try it asap even though it's 3.00 am here :-)   Please confirm this goes under   mqtt section ??

**Comment by msolomos** [comment]
First of all I can now confirm that it is Double-Take. These are the logs from Double-Take

> 24-02-14 02:29:12 error: IpDeniedError: Access denied to IP address: ::ffff:192.168.70.50
    at error (/double-take/api/node_modules/express-ipfilter/lib/ipfilter.js:156:17)
    at /double-take/api/node_modules/express-ipfilter/lib/ipfilter.js:202:12
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/double-take/api/node_modules/express/lib/router/index.js:328:13)
    at /double-take/api/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/double-take/api/node_modules/express/lib/router/index.js:346:12)
    at next (/double-take/api/node_modules/express/lib/router/index.js:280:10)
    at module.exports (/double-take/api/src/middlewares/respond.js:54:3)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
24-02-14 02:29:12 info: done processing frontdoor_camera2: 1707870551.489729-fcllqk in 0.75 sec
24-02-14 02:29:12 info: {
  id: '1707870551.489729-fcllqk',
  duration: 0.75,
  timestamp: '2024-02-14T00:29:12.651Z',
  attempts: 1,
  camera: 'frontdoor_camera2',
  zones: [],
  counts: { person: 1, match: 1, miss: 0, unknown: 0 },
  matches: [
    {
      name: 'makis',
      confidence: 99.58,
      match: true,
      box: [Object],
      type: 'latest',
      duration: 0.49,
      detector: 'compreface',
      filename: 'eac2ca47-3a7e-4c2d-abd7-b0e67ab657f9.jpg'
    }
  ],

However adding the **reject_unauthorized: false** didn't make the difference

`mqtt:
    host: 192.168.70.240
    port: 1883
    username: mqtt-user
    password: mosquitto
    
    tls:
      reject_unauthorized: false`


Damn, I am getting so close ...

**Comment by msolomos** [comment]
I am so exciting, I forgot to thank you!!!
THANK YOU!!!!!!!!!!!!!!!!!!!

**Comment by kmelihk** [comment]
You're welcome. your configuration is probably correct for double-take, there isn't really much to it. You don't have the line auth: true on your double-take config do you? That seems to enable authentication for both gui and api, that's the only thing I can think of that would block access. If you don't have it, you may want to check on double-take github.

**Comment by msolomos** [comment]
kmelihk, I want to trully thank you very much! It worked!!!
Am so happy.... and I really appreciate it very much that you helped me out. 

I had to reboot double-take and as soon as I did it, it worked!
Meanwhile, I've spent several hours and I managed to built the entire project in Visual Code studio.

This is almost ready to be an addon for HA. 
Maybe we should partner and make it happen ?? :-)
